services:
  - type: web
    name: fieldpro-web
    env: node
    region: ohio
    plan: starter # Puede ser free, starter, standard
    buildCommand: pnpm install && pnpm build
    startCommand: cd apps/web && pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PNPM_VERSION
        value: 9
      # Base de Datos
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      # Auth (Clerk)
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /dashboard
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /dashboard
      # AI Provider
      - key: AI_PROVIDER
        value: gemini
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      # Web / App Url
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      # Env
      - key: NODE_ENV
        value: production
